#!/bin/bash
m4 -D__INVAR__=$'hybrid_ideal_sim_invar1 func\'\n   (glob Hybrid){1} (glob IF){2} (glob SIM){2}\n   pt1\' pt2\' t\'' -D__CONSTRUCTOR__=HybridIdealSimInvar1 -D__HybridState__=HybridStateWaitAdv1 -D__EQ_OF_VALID__=KeyExchange.UC_KEI2S.eq_of_valid__ke_sim_rsp -D__NUM__=1 hybrid-ideal-sim-funct-seq.m4
