#!/bin/bash

# check all the UC common EasyCrypt scripts

# SMT timeout in seconds -- try increasing

timeout=2

check() {
  echo checking $1;
  if easycrypt -timeout $timeout $1;
  then echo passed: $1;
       echo "";
  else echo failed: $1;
       echo "";
       echo "skipping remaining scripts";
  exit 1;
  fi;
}

check UCListAux.ec
check UCListPO.ec
check UCEncoding.ec
check UCUniv.ec
check UCBasicTypes.ec
check UCCore.ec
check MakeRFExamp.ec
check UCComposition.ec
