#!/bin/bash
m4 -D__INVAR__=$'hybrid_ideal_sim_invar2 func\'\n   (glob Hybrid){1} (glob IF){2} (glob SIM){2}\n   pt1\' pt2\'\' q2\' q3\'' -D__CONSTRUCTOR__=HybridIdealSimInvar2 -D__NUM__=2 hybrid-ideal-sim-adv-seq1.m4
