#!/bin/bash

# check if option is good to supply to dsl-test, otherwise exit

if [[ $# -eq 1 ]];
then if [[ $1 != -quiet && $1 != -verbose ]];
     then echo optional argument must be -quiet or -verbose;
          exit 1;
     fi;
elif [[ $# -ne 0 ]];
  then echo illegal number of arguments;
       exit 1;
fi;

# remove old log, .coverage and CONFLICT files

find . -name log -type f -delete
find . -name "*.coverage" -type f -delete
find . -name CONFLICT -type f -delete

# run test suite

./dsl-test $* tests
status=$?

# generate bisect coverage report if there are some .coverage files

if [[ $(find . -name '*.coverage' | wc -l) -eq 0 ]];
then echo no coverage files generated;
else bisect-ppx-report html --coverage-path=./ --source-path=../ucdsl-proj --ignore-missing-files > bisect.log;
     echo bisect log is in bisect.log;
fi

exit $status
