#!/bin/bash

# script to update UC DSL source to include the current EasyCrypt
# source
#
# should only be run by a UC DSL developer, as changes in EasyCrypt
# could make UC DSL fail to build, or change its semantics in problematic
# ways

read -p 'Start the updating of EasyCrypt source in UC DSL? [yes/no] ' perm
if [ $perm != yes ];
then echo aborting;
     exit 1
fi

echo ""
echo "you need to enter the fully qualified pathname of the EasyCrypt "
echo "src directory (filename completion will be enabled)"
echo ""
read -e -p "EasyCrypt src directory pathname? " ecsrc
if [[ "$ecsrc" = *\'* ]];
  then echo ""
       echo "pathname cannot contain apostrophes"
       exit 1;
elif [[ "$ecsrc" = *\ * ]];
  then echo ""
       echo "pathname cannot contain spaces"
       exit 1;
elif [[ ! $ecsrc = /* ]];
  then echo ""
       echo "pathname is not fully qualified"
       exit 1;
elif [ ! -d $ecsrc ];
  then echo ""
       echo "pathname is not a directory";
       exit 1;
elif [ ! -e $ecsrc/ec.ml ];
  then echo ""
       echo "pathname is not the pathname of EasyCrypt src directory"
       exit 1;
fi

cd src/ECsrc

rm -rf phl system
rm *.{ml,mli} ecParser.mly ecLexer.mll

cp -r $ecsrc/phl .
cp -r $ecsrc/system .
cp $ecsrc/*.{ml,mli} .
cp $ecsrc/ecParser.mly .
cp $ecsrc/ecLexer.mll .
